version: '3'

networks:
  pxe-network:
    driver: bridge

services:
  matchbox:
    build:
      context: ..
      dockerfile: docker/Dockerfile.matchbox
    ports:
      - "8080:8080"
    environment:
      - GITHUB_REPO=https://github.com/quinneydavid/talos
    networks:
      - pxe-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - matchbox-assets:/var/lib/matchbox/assets

  matchbox-tftp:
    build:
      context: .
      dockerfile: Dockerfile.matchbox-tftp
    ports:
      - "69:69/udp"
    networks:
      - pxe-network
    volumes:
      - matchbox-assets:/var/lib/matchbox/assets:ro

volumes:
  matchbox-assets:
