version: '3'

networks:
  pxe-network:
    driver: bridge

volumes:
  matchbox-data:
    driver: local

services:
  matchbox:
    build:
      context: ..
      dockerfile: docker/Dockerfile.matchbox
    ports:
      - "8080:8080"
    environment:
      # GitHub repo for network-config.yaml (primary config source)
      - GITHUB_REPO=${GITHUB_REPO:-https://github.com/quinneydavid/talos}
      # Cluster ID to use (default: prod)
      - CLUSTER_ID=${CLUSTER_ID:-prod}
      # Other settings
      - WIPE_DISK=${WIPE_DISK:-true}
      - TALOS_VERSION=${TALOS_VERSION:-https://pxe.factory.talos.dev/pxe/c9078f9419961640c712a8bf2bb9174933dfcf1da383fd8ea2b7dc21493f8bac/v1.9.0/metal-amd64}
    networks:
      - pxe-network
    volumes:
      - matchbox-data:/var/lib/matchbox
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  matchbox-tftp:
    build:
      context: .
      dockerfile: Dockerfile.matchbox-tftp
    ports:
      - "69:69/udp"
    environment:
      - MATCHBOX_HOST=${MATCHBOX_HOST:-matchbox.lan}
    networks:
      - pxe-network
    volumes:
      - matchbox-data:/var/lib/matchbox:ro
    depends_on:
      - matchbox
