version: '3'

networks:
  pxe-network:
    driver: bridge

services:
  matchbox:
    build:
      context: .
      dockerfile: Dockerfile.matchbox
    ports:
      - "8080:8080"
    environment:
      - VAULT_ADDR=${VAULT_ADDR}
      - VAULT_TOKEN=${VAULT_TOKEN}
      - GITHUB_REPO=https://github.com/quinneydavid/talos
    networks:
      - pxe-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  matchbox-tftp:
    build:
      context: .
      dockerfile: Dockerfile.matchbox-tftp
    ports:
      - "69:69/udp"
    networks:
      - pxe-network
    volumes:
      - type: volume
        source: matchbox-assets
        target: /var/lib/matchbox/assets
        read_only: true

volumes:
  matchbox-assets:
