version: '3.8'

services:
  matchbox:
    build: 
      context: ..
      dockerfile: docker/Dockerfile.matchbox
      args:
        - GITHUB_REPO=https://github.com/quinneydavid/talos
    environment:
      - GITHUB_REPO=https://github.com/quinneydavid/talos
    volumes:
      - matchbox_data:/var/lib/matchbox
      - assets_data:/var/lib/matchbox/assets
    ports:
      - "8080:8080"
    networks:
      - pxe-network
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8080"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  matchbox-tftp:
    build:
      context: ..
      dockerfile: docker/Dockerfile.matchbox-tftp
    volumes:
      - tftp_data:/var/lib/tftpboot/assets:ro
    ports:
      - "69:69/udp"
    networks:
      - pxe-network
    depends_on:
      matchbox:
        condition: service_healthy

networks:
  pxe-network:
    driver: bridge

volumes:
  matchbox_data:
    driver: local
  tftp_data:
    driver: local
