version: '3'

networks:
  pxe-network:
    driver: bridge

volumes:
  matchbox-data:
    driver: local

services:
  matchbox:
    image: quinneyd/talos-matchbox:v1.9.0
    ports:
      - "8080:8080"
    environment:
      # GitHub repo for network-config.yaml (primary config source)
      - GITHUB_REPO=${GITHUB_REPO:-https://github.com/quinneydavid/talos}
      
      # Cluster ID to use (default: prod)
      - CLUSTER_ID=${CLUSTER_ID:-prod}
      
      # DNS suffix for node names
      - DNS_SUFFIX=${DNS_SUFFIX:-.lan}
      
      # Force regeneration of configs (default: false)
      - FORCE_REGENERATE=${FORCE_REGENERATE:-false}
      
      # Prod cluster sensitive information
      - PROD_VIP=${PROD_VIP}
      - PROD_NAME=${PROD_NAME}
      - PROD_ENDPOINT=${PROD_ENDPOINT}
      - PROD_DNS_DOMAIN=${PROD_DNS_DOMAIN}
      - PROD_POD_SUBNET=${PROD_POD_SUBNET}
      - PROD_SERVICE_SUBNET=${PROD_SERVICE_SUBNET}
      
      # Dev cluster sensitive information (uncomment when needed)
      # - DEV_VIP=${DEV_VIP}
      # - DEV_NAME=${DEV_NAME}
      # - DEV_ENDPOINT=${DEV_ENDPOINT}
      # - DEV_DNS_DOMAIN=${DEV_DNS_DOMAIN}
      # - DEV_POD_SUBNET=${DEV_POD_SUBNET}
      # - DEV_SERVICE_SUBNET=${DEV_SERVICE_SUBNET}
      
      # Other settings
      - WIPE_DISK=${WIPE_DISK:-true}
      - TALOS_VERSION=${TALOS_VERSION:-https://pxe.factory.talos.dev/pxe/c9078f9419961640c712a8bf2bb9174933dfcf1da383fd8ea2b7dc21493f8bac/v1.9.0/metal-amd64}
    networks:
      - pxe-network
    volumes:
      - matchbox-data:/var/lib/matchbox
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  matchbox-tftp:
    image: quinneyd/talos-matchbox-tftp:v1.9.0
    ports:
      - "69:69/udp"
    environment:
      - MATCHBOX_HOST=${MATCHBOX_HOST:-matchbox.lan}
      - CLUSTER_ID=${CLUSTER_ID:-prod}
      - DNS_SUFFIX=${DNS_SUFFIX:-.lan}
    networks:
      - pxe-network
    volumes:
      - matchbox-data:/var/lib/matchbox:ro
    depends_on:
      - matchbox
      
  talos-bootstrap:
    image: quinneyd/talos-bootstrap:v1.9.0
    environment:
      - CLUSTER_ID=${CLUSTER_ID:-prod}
      - BOOTSTRAP_POLICY=${BOOTSTRAP_POLICY:-wait}
      - BOOTSTRAP_WAIT_TIME=${BOOTSTRAP_WAIT_TIME:-300}
      - BOOTSTRAP_RETRY_INTERVAL=${BOOTSTRAP_RETRY_INTERVAL:-30}
      - DNS_SUFFIX=${DNS_SUFFIX:-.lan}
    networks:
      - pxe-network
    volumes:
      - matchbox-data:/var/lib/matchbox:ro
      - ${HOME}/.kube:/root/.kube
      - ${HOME}/.talos:/root/.talos
    restart: "no"
    depends_on:
      - matchbox
