# Global network settings
network:
  vip: "10.88.8.210"  # VIP for Kubernetes API

# Node-specific configurations (using DHCP)
nodes:
  prodcp1:
    mac: "50:6b:8d:96:f7:50"
    hostname: "prodcp1"
    type: "controlplane"

  prodcp2:
    mac: "50:6b:8d:e3:2e:e7"
    hostname: "prodcp2"
    type: "controlplane"

  prodcp3:
    mac: "50:6b:8d:be:b5:e5"
    hostname: "prodcp3"
    type: "controlplane"

  prodworker1:
    mac: "50:6b:8d:ff:7b:7e"
    hostname: "prodworker1"
    type: "worker"

  prodworker2:
    mac: "50:6b:8d:91:08:d3"
    hostname: "prodworker2"
    type: "worker"
