# Global network settings
network:
  vip: "10.88.8.210"  # VIP for Kubernetes API

# Node-specific configurations (using DHCP)
nodes:
  cp1:
    mac: "50:6b:8d:96:f7:50"
    hostname: "cp1"
    type: "controlplane"

  cp2:
    mac: "50:6b:8d:e3:2e:e7"
    hostname: "cp2"
    type: "controlplane"

  cp3:
    mac: "50:6b:8d:be:b5:e5"
    hostname: "cp3"
    type: "controlplane"

  worker1:
    mac: "50:6b:8d:ff:7b:7e"
    hostname: "worker1"
    type: "worker"

  worker2:
    mac: "50:6b:8d:91:08:d3"
    hostname: "worker2"
    type: "worker"
