apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: synology-test-pvc
spec:
  storageClassName: synology-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: storage-test
spec:
  tolerations:
  - key: node-role.kubernetes.io/control-plane
    operator: Exists
    effect: NoSchedule
  containers:
  - name: storage-test
    image: busybox
    command:
    - /bin/sh
    - -c
    - echo 'Testing Synology storage!' > /data/test.txt && cat /data/test.txt && sleep 3600
    volumeMounts:
    - name: synology-storage
      mountPath: /data
  volumes:
  - name: synology-storage
    persistentVolumeClaim:
      claimName: synology-test-pvc
