apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: synology-iscsi
provisioner: csi.san.synology.com
parameters:
  dsm: "10.44.5.2"
  location: "/volume1"
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
