apiVersion: v1
kind: ConfigMap
metadata:
  name: synology-csi-config
  namespace: kube-system
data:
  "client-info.yml": |
    clients:
      - host: 10.44.5.2
        port: 5000
        https: false
        username: synology-csi
        password: "^PsjMQ7BEnfHH"
---
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: csi.san.synology.com
spec:
  attachRequired: true
  podInfoOnMount: false
  volumeLifecycleModes:
    - Persistent
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: synology-csi-node
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: synology-csi-node
  template:
    metadata:
      labels:
        app: synology-csi-node
    spec:
      hostNetwork: true
      initContainers:
        - name: init-dirs
          image: busybox
          command: ['sh', '-c', 'mkdir -p /registration/csi.san.synology.com /var/lib/kubelet/plugins/csi.san.synology.com']
          volumeMounts:
            - name: registration-dir
              mountPath: /registration
            - name: plugin-dir
              mountPath: /var/lib/kubelet/plugins/csi.san.synology.com
      containers:
        - name: synology-csi-plugin
          image: synology/synology-csi:v1.1.0
          securityContext:
            privileged: true
          env:
            - name: CSI_ENDPOINT
              value: unix:///var/lib/kubelet/plugins/csi.san.synology.com/csi.sock
            - name: CSI_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: registration-dir
              mountPath: /registration
            - name: plugin-dir
              mountPath: /var/lib/kubelet/plugins/csi.san.synology.com
            - name: pods-mount-dir
              mountPath: /var/lib/kubelet/pods
              mountPropagation: "Bidirectional"
            - name: host-dev
              mountPath: /dev
            - name: host-sys
              mountPath: /sys
            - name: lib-modules
              mountPath: /lib/modules
              readOnly: true
            - name: synology-config
              mountPath: /etc/synology/client-info.yml
              subPath: client-info.yml
      volumes:
        - name: registration-dir
          hostPath:
            path: /var/lib/kubelet/plugins_registry
            type: DirectoryOrCreate
        - name: plugin-dir
          hostPath:
            path: /var/lib/kubelet/plugins/csi.san.synology.com
            type: DirectoryOrCreate
        - name: pods-mount-dir
          hostPath:
            path: /var/lib/kubelet/pods
            type: Directory
        - name: host-dev
          hostPath:
            path: /dev
        - name: host-sys
          hostPath:
            path: /sys
        - name: lib-modules
          hostPath:
            path: /lib/modules
        - name: synology-config
          configMap:
            name: synology-csi-config
