apiVersion: v1
kind: Pod
metadata:
  name: network-test-2
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
  - name: network-test
    image: curlimages/curl
    command: ['sh', '-c', 'curl -v http://10.44.5.2:5000/webapi/auth.cgi?account=synology-csi&api=SYNO.API.Auth&format=sid&method=login&version=3']
